# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to @flavioespinoza/salsa-ui to NPM

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 'change version'
        uses: dmikey/package-json-version@v0.0.2
        with:
          version: ${{ steps.get_release.outputs.tag_name }}
          package: './'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:module

      - name: NPM Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.npm_token }}" > ~/.npmrc
          npm publish --access public
